##### MQTT temp sensor examples (Tasmota)

sensor:
  - name: "Outdoors temperature"
    state_topic: "tele/outdoors/SENSOR"
    value_template: "{{ value_json['DS18B20'].Temperature }}"
    unit_of_measurement: "°C"
    force_update: true
    availability_topic: "tele/outdoors/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"
    unique_id: temp_out

  - name: "Room1 temperature"
    state_topic: "tele/room1/SENSOR"
    value_template: "{{ value_json['DS18B20'].Temperature }}"
    unit_of_measurement: "°C"
    device_class: temperature
    force_update: true
    availability_topic: "tele/room1/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"
    unique_id: temp_room1

  - name: "Room2 temperature"
    state_topic: "tele/room2/SENSOR"
    value_template: "{{ value_json['DS18B20'].Temperature }}"
    unit_of_measurement: "°C"
    device_class: temperature
    force_update: true
    availability_topic: "tele/room2/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"
    unique_id: temp_room2

  - name: "Room3 temperature"
    state_topic: "tele/room3/SENSOR"
    value_template: "{{ value_json['DS18B20'].Temperature }}"
    unit_of_measurement: "°C"
    device_class: temperature
    force_update: true
    availability_topic: "tele/room3/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"
    unique_id: temp_room3

  - name: "Room4 temperature"
    state_topic: "tele/room4/SENSOR"
    value_template: "{{ value_json['DS18B20'].Temperature }}"
    unit_of_measurement: "°C"
    device_class: temperature
    force_update: true
    availability_topic: "tele/room4/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"
    unique_id: temp_room4