- platform: template
  sensors:
    weather_forecast_temperature:
      friendly_name: "Temperature from weather forecast"
      unit_of_measurement: '°C'
      value_template: "{{ state_attr('weather.openweathermap','forecast')[1]['temperature'] }}"

#    average_rooms_temperature:  # Not too good like this, because it doesn't show accurate values when a sensor is missing/unavailable. Using 'average' csutom component (https://github.com/Limych/ha-average) is more accurate as it handles this situation.
#      unit_of_measurement: '°C'
#      friendly_name: "Average rooms temperature"
#      value_template: >-
#        {{ ((float(states.sensor.room1_temperature.state) + float(states.sensor.room2_temperature.state) + float(states.sensor.room3_temperature.state) + float(states.sensor.room4_temperature.state)) / 4) | round(2) }}

